### ISSUE TITLE
Error in the volume

### ISSUE THREAD

**Issue by minchen57** [cloudmesh-community/hid-sp18-419#62]
I found the volume of project at [here](http://cyberaide.org/papers/vonLaszewski-cloud-vol-9.pdf)

In the content, for our paper, it says error, title not found. 

we need to check what is happening

**Comment by bsobolik** [comment]
I think maybe it was that typo that Prof. von Laszewski found. It all compiles for me. There are still warnings about line length for the figures, but I think adding carriage returns in those creates errors so I left them. I couldn't get the ifconfig output to work as a figure, so I took it out.
